/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { TimeSeriesData } from "./TimeSeriesData";
import { TimeSeriesDataCountArgs } from "./TimeSeriesDataCountArgs";
import { TimeSeriesDataFindManyArgs } from "./TimeSeriesDataFindManyArgs";
import { TimeSeriesDataFindUniqueArgs } from "./TimeSeriesDataFindUniqueArgs";
import { CreateTimeSeriesDataArgs } from "./CreateTimeSeriesDataArgs";
import { UpdateTimeSeriesDataArgs } from "./UpdateTimeSeriesDataArgs";
import { DeleteTimeSeriesDataArgs } from "./DeleteTimeSeriesDataArgs";
import { StringModel } from "../../stringModel/base/StringModel";
import { TimeSeriesDataService } from "../timeSeriesData.service";
@graphql.Resolver(() => TimeSeriesData)
export class TimeSeriesDataResolverBase {
  constructor(protected readonly service: TimeSeriesDataService) {}

  async _timeSeriesDataItemsMeta(
    @graphql.Args() args: TimeSeriesDataCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [TimeSeriesData])
  async timeSeriesDataItems(
    @graphql.Args() args: TimeSeriesDataFindManyArgs
  ): Promise<TimeSeriesData[]> {
    return this.service.timeSeriesDataItems(args);
  }

  @graphql.Query(() => TimeSeriesData, { nullable: true })
  async timeSeriesData(
    @graphql.Args() args: TimeSeriesDataFindUniqueArgs
  ): Promise<TimeSeriesData | null> {
    const result = await this.service.timeSeriesData(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => TimeSeriesData)
  async createTimeSeriesData(
    @graphql.Args() args: CreateTimeSeriesDataArgs
  ): Promise<TimeSeriesData> {
    return await this.service.createTimeSeriesData({
      ...args,
      data: {
        ...args.data,

        stringField: args.data.stringField
          ? {
              connect: args.data.stringField,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => TimeSeriesData)
  async updateTimeSeriesData(
    @graphql.Args() args: UpdateTimeSeriesDataArgs
  ): Promise<TimeSeriesData | null> {
    try {
      return await this.service.updateTimeSeriesData({
        ...args,
        data: {
          ...args.data,

          stringField: args.data.stringField
            ? {
                connect: args.data.stringField,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => TimeSeriesData)
  async deleteTimeSeriesData(
    @graphql.Args() args: DeleteTimeSeriesDataArgs
  ): Promise<TimeSeriesData | null> {
    try {
      return await this.service.deleteTimeSeriesData(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => StringModel, {
    nullable: true,
    name: "stringField",
  })
  async getStringField(
    @graphql.Parent() parent: TimeSeriesData
  ): Promise<StringModel | null> {
    const result = await this.service.getStringField(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
