/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { TimeSeriesDataService } from "../timeSeriesData.service";
import { TimeSeriesDataCreateInput } from "./TimeSeriesDataCreateInput";
import { TimeSeriesData } from "./TimeSeriesData";
import { TimeSeriesDataFindManyArgs } from "./TimeSeriesDataFindManyArgs";
import { TimeSeriesDataWhereUniqueInput } from "./TimeSeriesDataWhereUniqueInput";
import { TimeSeriesDataUpdateInput } from "./TimeSeriesDataUpdateInput";

export class TimeSeriesDataControllerBase {
  constructor(protected readonly service: TimeSeriesDataService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: TimeSeriesData })
  async createTimeSeriesData(
    @common.Body() data: TimeSeriesDataCreateInput
  ): Promise<TimeSeriesData> {
    return await this.service.createTimeSeriesData({
      data: {
        ...data,

        stringField: data.stringField
          ? {
              connect: data.stringField,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,
        metricType: true,

        stringField: {
          select: {
            id: true,
          },
        },

        timestamp: true,
        updatedAt: true,
        value: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [TimeSeriesData] })
  @ApiNestedQuery(TimeSeriesDataFindManyArgs)
  async timeSeriesDataItems(
    @common.Req() request: Request
  ): Promise<TimeSeriesData[]> {
    const args = plainToClass(TimeSeriesDataFindManyArgs, request.query);
    return this.service.timeSeriesDataItems({
      ...args,
      select: {
        createdAt: true,
        id: true,
        metricType: true,

        stringField: {
          select: {
            id: true,
          },
        },

        timestamp: true,
        updatedAt: true,
        value: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: TimeSeriesData })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async timeSeriesData(
    @common.Param() params: TimeSeriesDataWhereUniqueInput
  ): Promise<TimeSeriesData | null> {
    const result = await this.service.timeSeriesData({
      where: params,
      select: {
        createdAt: true,
        id: true,
        metricType: true,

        stringField: {
          select: {
            id: true,
          },
        },

        timestamp: true,
        updatedAt: true,
        value: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: TimeSeriesData })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateTimeSeriesData(
    @common.Param() params: TimeSeriesDataWhereUniqueInput,
    @common.Body() data: TimeSeriesDataUpdateInput
  ): Promise<TimeSeriesData | null> {
    try {
      return await this.service.updateTimeSeriesData({
        where: params,
        data: {
          ...data,

          stringField: data.stringField
            ? {
                connect: data.stringField,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,
          metricType: true,

          stringField: {
            select: {
              id: true,
            },
          },

          timestamp: true,
          updatedAt: true,
          value: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: TimeSeriesData })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteTimeSeriesData(
    @common.Param() params: TimeSeriesDataWhereUniqueInput
  ): Promise<TimeSeriesData | null> {
    try {
      return await this.service.deleteTimeSeriesData({
        where: params,
        select: {
          createdAt: true,
          id: true,
          metricType: true,

          stringField: {
            select: {
              id: true,
            },
          },

          timestamp: true,
          updatedAt: true,
          value: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
