/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  TimeSeriesData as PrismaTimeSeriesData,
  StringModel as PrismaStringModel,
} from "@prisma/client";

export class TimeSeriesDataServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.TimeSeriesDataCountArgs, "select">
  ): Promise<number> {
    return this.prisma.timeSeriesData.count(args);
  }

  async timeSeriesDataItems(
    args: Prisma.TimeSeriesDataFindManyArgs
  ): Promise<PrismaTimeSeriesData[]> {
    return this.prisma.timeSeriesData.findMany(args);
  }
  async timeSeriesData(
    args: Prisma.TimeSeriesDataFindUniqueArgs
  ): Promise<PrismaTimeSeriesData | null> {
    return this.prisma.timeSeriesData.findUnique(args);
  }
  async createTimeSeriesData(
    args: Prisma.TimeSeriesDataCreateArgs
  ): Promise<PrismaTimeSeriesData> {
    return this.prisma.timeSeriesData.create(args);
  }
  async updateTimeSeriesData(
    args: Prisma.TimeSeriesDataUpdateArgs
  ): Promise<PrismaTimeSeriesData> {
    return this.prisma.timeSeriesData.update(args);
  }
  async deleteTimeSeriesData(
    args: Prisma.TimeSeriesDataDeleteArgs
  ): Promise<PrismaTimeSeriesData> {
    return this.prisma.timeSeriesData.delete(args);
  }

  async getStringField(parentId: string): Promise<PrismaStringModel | null> {
    return this.prisma.timeSeriesData
      .findUnique({
        where: { id: parentId },
      })
      .stringField();
  }
}
