/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  SolarInstallation as PrismaSolarInstallation,
  Inverter as PrismaInverter,
} from "@prisma/client";

export class SolarInstallationServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.SolarInstallationCountArgs, "select">
  ): Promise<number> {
    return this.prisma.solarInstallation.count(args);
  }

  async solarInstallations(
    args: Prisma.SolarInstallationFindManyArgs
  ): Promise<PrismaSolarInstallation[]> {
    return this.prisma.solarInstallation.findMany(args);
  }
  async solarInstallation(
    args: Prisma.SolarInstallationFindUniqueArgs
  ): Promise<PrismaSolarInstallation | null> {
    return this.prisma.solarInstallation.findUnique(args);
  }
  async createSolarInstallation(
    args: Prisma.SolarInstallationCreateArgs
  ): Promise<PrismaSolarInstallation> {
    return this.prisma.solarInstallation.create(args);
  }
  async updateSolarInstallation(
    args: Prisma.SolarInstallationUpdateArgs
  ): Promise<PrismaSolarInstallation> {
    return this.prisma.solarInstallation.update(args);
  }
  async deleteSolarInstallation(
    args: Prisma.SolarInstallationDeleteArgs
  ): Promise<PrismaSolarInstallation> {
    return this.prisma.solarInstallation.delete(args);
  }

  async findInverters(
    parentId: string,
    args: Prisma.InverterFindManyArgs
  ): Promise<PrismaInverter[]> {
    return this.prisma.solarInstallation
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .inverters(args);
  }
}
