/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { SolarInstallationService } from "../solarInstallation.service";
import { SolarInstallationCreateInput } from "./SolarInstallationCreateInput";
import { SolarInstallation } from "./SolarInstallation";
import { SolarInstallationFindManyArgs } from "./SolarInstallationFindManyArgs";
import { SolarInstallationWhereUniqueInput } from "./SolarInstallationWhereUniqueInput";
import { SolarInstallationUpdateInput } from "./SolarInstallationUpdateInput";
import { InverterFindManyArgs } from "../../inverter/base/InverterFindManyArgs";
import { Inverter } from "../../inverter/base/Inverter";
import { InverterWhereUniqueInput } from "../../inverter/base/InverterWhereUniqueInput";

export class SolarInstallationControllerBase {
  constructor(protected readonly service: SolarInstallationService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: SolarInstallation })
  async createSolarInstallation(
    @common.Body() data: SolarInstallationCreateInput
  ): Promise<SolarInstallation> {
    return await this.service.createSolarInstallation({
      data: data,
      select: {
        createdAt: true,
        id: true,
        installedAt: true,
        location: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [SolarInstallation] })
  @ApiNestedQuery(SolarInstallationFindManyArgs)
  async solarInstallations(
    @common.Req() request: Request
  ): Promise<SolarInstallation[]> {
    const args = plainToClass(SolarInstallationFindManyArgs, request.query);
    return this.service.solarInstallations({
      ...args,
      select: {
        createdAt: true,
        id: true,
        installedAt: true,
        location: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: SolarInstallation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async solarInstallation(
    @common.Param() params: SolarInstallationWhereUniqueInput
  ): Promise<SolarInstallation | null> {
    const result = await this.service.solarInstallation({
      where: params,
      select: {
        createdAt: true,
        id: true,
        installedAt: true,
        location: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: SolarInstallation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateSolarInstallation(
    @common.Param() params: SolarInstallationWhereUniqueInput,
    @common.Body() data: SolarInstallationUpdateInput
  ): Promise<SolarInstallation | null> {
    try {
      return await this.service.updateSolarInstallation({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          installedAt: true,
          location: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: SolarInstallation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteSolarInstallation(
    @common.Param() params: SolarInstallationWhereUniqueInput
  ): Promise<SolarInstallation | null> {
    try {
      return await this.service.deleteSolarInstallation({
        where: params,
        select: {
          createdAt: true,
          id: true,
          installedAt: true,
          location: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/inverters")
  @ApiNestedQuery(InverterFindManyArgs)
  async findInverters(
    @common.Req() request: Request,
    @common.Param() params: SolarInstallationWhereUniqueInput
  ): Promise<Inverter[]> {
    const query = plainToClass(InverterFindManyArgs, request.query);
    const results = await this.service.findInverters(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        model: true,
        serialNumber: true,

        solarInstallation: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/inverters")
  async connectInverters(
    @common.Param() params: SolarInstallationWhereUniqueInput,
    @common.Body() body: InverterWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      inverters: {
        connect: body,
      },
    };
    await this.service.updateSolarInstallation({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/inverters")
  async updateInverters(
    @common.Param() params: SolarInstallationWhereUniqueInput,
    @common.Body() body: InverterWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      inverters: {
        set: body,
      },
    };
    await this.service.updateSolarInstallation({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/inverters")
  async disconnectInverters(
    @common.Param() params: SolarInstallationWhereUniqueInput,
    @common.Body() body: InverterWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      inverters: {
        disconnect: body,
      },
    };
    await this.service.updateSolarInstallation({
      where: params,
      data,
      select: { id: true },
    });
  }
}
