/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { SolarInstallation } from "./SolarInstallation";
import { SolarInstallationCountArgs } from "./SolarInstallationCountArgs";
import { SolarInstallationFindManyArgs } from "./SolarInstallationFindManyArgs";
import { SolarInstallationFindUniqueArgs } from "./SolarInstallationFindUniqueArgs";
import { CreateSolarInstallationArgs } from "./CreateSolarInstallationArgs";
import { UpdateSolarInstallationArgs } from "./UpdateSolarInstallationArgs";
import { DeleteSolarInstallationArgs } from "./DeleteSolarInstallationArgs";
import { InverterFindManyArgs } from "../../inverter/base/InverterFindManyArgs";
import { Inverter } from "../../inverter/base/Inverter";
import { SolarInstallationService } from "../solarInstallation.service";
@graphql.Resolver(() => SolarInstallation)
export class SolarInstallationResolverBase {
  constructor(protected readonly service: SolarInstallationService) {}

  async _solarInstallationsMeta(
    @graphql.Args() args: SolarInstallationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [SolarInstallation])
  async solarInstallations(
    @graphql.Args() args: SolarInstallationFindManyArgs
  ): Promise<SolarInstallation[]> {
    return this.service.solarInstallations(args);
  }

  @graphql.Query(() => SolarInstallation, { nullable: true })
  async solarInstallation(
    @graphql.Args() args: SolarInstallationFindUniqueArgs
  ): Promise<SolarInstallation | null> {
    const result = await this.service.solarInstallation(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => SolarInstallation)
  async createSolarInstallation(
    @graphql.Args() args: CreateSolarInstallationArgs
  ): Promise<SolarInstallation> {
    return await this.service.createSolarInstallation({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => SolarInstallation)
  async updateSolarInstallation(
    @graphql.Args() args: UpdateSolarInstallationArgs
  ): Promise<SolarInstallation | null> {
    try {
      return await this.service.updateSolarInstallation({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => SolarInstallation)
  async deleteSolarInstallation(
    @graphql.Args() args: DeleteSolarInstallationArgs
  ): Promise<SolarInstallation | null> {
    try {
      return await this.service.deleteSolarInstallation(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Inverter], { name: "inverters" })
  async findInverters(
    @graphql.Parent() parent: SolarInstallation,
    @graphql.Args() args: InverterFindManyArgs
  ): Promise<Inverter[]> {
    const results = await this.service.findInverters(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
