/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Inverter as PrismaInverter,
  StringModel as PrismaStringModel,
  SolarInstallation as PrismaSolarInstallation,
} from "@prisma/client";

export class InverterServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.InverterCountArgs, "select">): Promise<number> {
    return this.prisma.inverter.count(args);
  }

  async inverters(
    args: Prisma.InverterFindManyArgs
  ): Promise<PrismaInverter[]> {
    return this.prisma.inverter.findMany(args);
  }
  async inverter(
    args: Prisma.InverterFindUniqueArgs
  ): Promise<PrismaInverter | null> {
    return this.prisma.inverter.findUnique(args);
  }
  async createInverter(
    args: Prisma.InverterCreateArgs
  ): Promise<PrismaInverter> {
    return this.prisma.inverter.create(args);
  }
  async updateInverter(
    args: Prisma.InverterUpdateArgs
  ): Promise<PrismaInverter> {
    return this.prisma.inverter.update(args);
  }
  async deleteInverter(
    args: Prisma.InverterDeleteArgs
  ): Promise<PrismaInverter> {
    return this.prisma.inverter.delete(args);
  }

  async findStrings(
    parentId: string,
    args: Prisma.StringModelFindManyArgs
  ): Promise<PrismaStringModel[]> {
    return this.prisma.inverter
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .strings(args);
  }

  async getSolarInstallation(
    parentId: string
  ): Promise<PrismaSolarInstallation | null> {
    return this.prisma.inverter
      .findUnique({
        where: { id: parentId },
      })
      .solarInstallation();
  }
}
