/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { InverterService } from "../inverter.service";
import { InverterCreateInput } from "./InverterCreateInput";
import { Inverter } from "./Inverter";
import { InverterFindManyArgs } from "./InverterFindManyArgs";
import { InverterWhereUniqueInput } from "./InverterWhereUniqueInput";
import { InverterUpdateInput } from "./InverterUpdateInput";
import { StringModelFindManyArgs } from "../../stringModel/base/StringModelFindManyArgs";
import { StringModel } from "../../stringModel/base/StringModel";
import { StringModelWhereUniqueInput } from "../../stringModel/base/StringModelWhereUniqueInput";

export class InverterControllerBase {
  constructor(protected readonly service: InverterService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Inverter })
  async createInverter(
    @common.Body() data: InverterCreateInput
  ): Promise<Inverter> {
    return await this.service.createInverter({
      data: {
        ...data,

        solarInstallation: data.solarInstallation
          ? {
              connect: data.solarInstallation,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,
        model: true,
        serialNumber: true,

        solarInstallation: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Inverter] })
  @ApiNestedQuery(InverterFindManyArgs)
  async inverters(@common.Req() request: Request): Promise<Inverter[]> {
    const args = plainToClass(InverterFindManyArgs, request.query);
    return this.service.inverters({
      ...args,
      select: {
        createdAt: true,
        id: true,
        model: true,
        serialNumber: true,

        solarInstallation: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Inverter })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async inverter(
    @common.Param() params: InverterWhereUniqueInput
  ): Promise<Inverter | null> {
    const result = await this.service.inverter({
      where: params,
      select: {
        createdAt: true,
        id: true,
        model: true,
        serialNumber: true,

        solarInstallation: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Inverter })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateInverter(
    @common.Param() params: InverterWhereUniqueInput,
    @common.Body() data: InverterUpdateInput
  ): Promise<Inverter | null> {
    try {
      return await this.service.updateInverter({
        where: params,
        data: {
          ...data,

          solarInstallation: data.solarInstallation
            ? {
                connect: data.solarInstallation,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,
          model: true,
          serialNumber: true,

          solarInstallation: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Inverter })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteInverter(
    @common.Param() params: InverterWhereUniqueInput
  ): Promise<Inverter | null> {
    try {
      return await this.service.deleteInverter({
        where: params,
        select: {
          createdAt: true,
          id: true,
          model: true,
          serialNumber: true,

          solarInstallation: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/strings")
  @ApiNestedQuery(StringModelFindManyArgs)
  async findStrings(
    @common.Req() request: Request,
    @common.Param() params: InverterWhereUniqueInput
  ): Promise<StringModel[]> {
    const query = plainToClass(StringModelFindManyArgs, request.query);
    const results = await this.service.findStrings(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        identifier: true,

        inverter: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/strings")
  async connectStrings(
    @common.Param() params: InverterWhereUniqueInput,
    @common.Body() body: StringModelWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      strings: {
        connect: body,
      },
    };
    await this.service.updateInverter({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/strings")
  async updateStrings(
    @common.Param() params: InverterWhereUniqueInput,
    @common.Body() body: StringModelWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      strings: {
        set: body,
      },
    };
    await this.service.updateInverter({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/strings")
  async disconnectStrings(
    @common.Param() params: InverterWhereUniqueInput,
    @common.Body() body: StringModelWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      strings: {
        disconnect: body,
      },
    };
    await this.service.updateInverter({
      where: params,
      data,
      select: { id: true },
    });
  }
}
