/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  StringModel as PrismaStringModel,
  Anomaly as PrismaAnomaly,
  TimeSeriesData as PrismaTimeSeriesData,
  Inverter as PrismaInverter,
} from "@prisma/client";

export class StringModelServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.StringModelCountArgs, "select">
  ): Promise<number> {
    return this.prisma.stringModel.count(args);
  }

  async stringModels(
    args: Prisma.StringModelFindManyArgs
  ): Promise<PrismaStringModel[]> {
    return this.prisma.stringModel.findMany(args);
  }
  async stringModel(
    args: Prisma.StringModelFindUniqueArgs
  ): Promise<PrismaStringModel | null> {
    return this.prisma.stringModel.findUnique(args);
  }
  async createStringModel(
    args: Prisma.StringModelCreateArgs
  ): Promise<PrismaStringModel> {
    return this.prisma.stringModel.create(args);
  }
  async updateStringModel(
    args: Prisma.StringModelUpdateArgs
  ): Promise<PrismaStringModel> {
    return this.prisma.stringModel.update(args);
  }
  async deleteStringModel(
    args: Prisma.StringModelDeleteArgs
  ): Promise<PrismaStringModel> {
    return this.prisma.stringModel.delete(args);
  }

  async findAnomalies(
    parentId: string,
    args: Prisma.AnomalyFindManyArgs
  ): Promise<PrismaAnomaly[]> {
    return this.prisma.stringModel
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .anomalies(args);
  }

  async findTimeSeriesDataItems(
    parentId: string,
    args: Prisma.TimeSeriesDataFindManyArgs
  ): Promise<PrismaTimeSeriesData[]> {
    return this.prisma.stringModel
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .timeSeriesDataItems(args);
  }

  async getInverter(parentId: string): Promise<PrismaInverter | null> {
    return this.prisma.stringModel
      .findUnique({
        where: { id: parentId },
      })
      .inverter();
  }
}
