/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { StringModel } from "./StringModel";
import { StringModelCountArgs } from "./StringModelCountArgs";
import { StringModelFindManyArgs } from "./StringModelFindManyArgs";
import { StringModelFindUniqueArgs } from "./StringModelFindUniqueArgs";
import { CreateStringModelArgs } from "./CreateStringModelArgs";
import { UpdateStringModelArgs } from "./UpdateStringModelArgs";
import { DeleteStringModelArgs } from "./DeleteStringModelArgs";
import { AnomalyFindManyArgs } from "../../anomaly/base/AnomalyFindManyArgs";
import { Anomaly } from "../../anomaly/base/Anomaly";
import { TimeSeriesDataFindManyArgs } from "../../timeSeriesData/base/TimeSeriesDataFindManyArgs";
import { TimeSeriesData } from "../../timeSeriesData/base/TimeSeriesData";
import { Inverter } from "../../inverter/base/Inverter";
import { StringModelService } from "../stringModel.service";
@graphql.Resolver(() => StringModel)
export class StringModelResolverBase {
  constructor(protected readonly service: StringModelService) {}

  async _stringModelsMeta(
    @graphql.Args() args: StringModelCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [StringModel])
  async stringModels(
    @graphql.Args() args: StringModelFindManyArgs
  ): Promise<StringModel[]> {
    return this.service.stringModels(args);
  }

  @graphql.Query(() => StringModel, { nullable: true })
  async stringModel(
    @graphql.Args() args: StringModelFindUniqueArgs
  ): Promise<StringModel | null> {
    const result = await this.service.stringModel(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => StringModel)
  async createStringModel(
    @graphql.Args() args: CreateStringModelArgs
  ): Promise<StringModel> {
    return await this.service.createStringModel({
      ...args,
      data: {
        ...args.data,

        inverter: args.data.inverter
          ? {
              connect: args.data.inverter,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => StringModel)
  async updateStringModel(
    @graphql.Args() args: UpdateStringModelArgs
  ): Promise<StringModel | null> {
    try {
      return await this.service.updateStringModel({
        ...args,
        data: {
          ...args.data,

          inverter: args.data.inverter
            ? {
                connect: args.data.inverter,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => StringModel)
  async deleteStringModel(
    @graphql.Args() args: DeleteStringModelArgs
  ): Promise<StringModel | null> {
    try {
      return await this.service.deleteStringModel(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Anomaly], { name: "anomalies" })
  async findAnomalies(
    @graphql.Parent() parent: StringModel,
    @graphql.Args() args: AnomalyFindManyArgs
  ): Promise<Anomaly[]> {
    const results = await this.service.findAnomalies(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [TimeSeriesData], { name: "timeSeriesDataItems" })
  async findTimeSeriesDataItems(
    @graphql.Parent() parent: StringModel,
    @graphql.Args() args: TimeSeriesDataFindManyArgs
  ): Promise<TimeSeriesData[]> {
    const results = await this.service.findTimeSeriesDataItems(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => Inverter, {
    nullable: true,
    name: "inverter",
  })
  async getInverter(
    @graphql.Parent() parent: StringModel
  ): Promise<Inverter | null> {
    const result = await this.service.getInverter(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
