/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { StringModelService } from "../stringModel.service";
import { StringModelCreateInput } from "./StringModelCreateInput";
import { StringModel } from "./StringModel";
import { StringModelFindManyArgs } from "./StringModelFindManyArgs";
import { StringModelWhereUniqueInput } from "./StringModelWhereUniqueInput";
import { StringModelUpdateInput } from "./StringModelUpdateInput";
import { AnomalyFindManyArgs } from "../../anomaly/base/AnomalyFindManyArgs";
import { Anomaly } from "../../anomaly/base/Anomaly";
import { AnomalyWhereUniqueInput } from "../../anomaly/base/AnomalyWhereUniqueInput";
import { TimeSeriesDataFindManyArgs } from "../../timeSeriesData/base/TimeSeriesDataFindManyArgs";
import { TimeSeriesData } from "../../timeSeriesData/base/TimeSeriesData";
import { TimeSeriesDataWhereUniqueInput } from "../../timeSeriesData/base/TimeSeriesDataWhereUniqueInput";

export class StringModelControllerBase {
  constructor(protected readonly service: StringModelService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: StringModel })
  async createStringModel(
    @common.Body() data: StringModelCreateInput
  ): Promise<StringModel> {
    return await this.service.createStringModel({
      data: {
        ...data,

        inverter: data.inverter
          ? {
              connect: data.inverter,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,
        identifier: true,

        inverter: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [StringModel] })
  @ApiNestedQuery(StringModelFindManyArgs)
  async stringModels(@common.Req() request: Request): Promise<StringModel[]> {
    const args = plainToClass(StringModelFindManyArgs, request.query);
    return this.service.stringModels({
      ...args,
      select: {
        createdAt: true,
        id: true,
        identifier: true,

        inverter: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: StringModel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async stringModel(
    @common.Param() params: StringModelWhereUniqueInput
  ): Promise<StringModel | null> {
    const result = await this.service.stringModel({
      where: params,
      select: {
        createdAt: true,
        id: true,
        identifier: true,

        inverter: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: StringModel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateStringModel(
    @common.Param() params: StringModelWhereUniqueInput,
    @common.Body() data: StringModelUpdateInput
  ): Promise<StringModel | null> {
    try {
      return await this.service.updateStringModel({
        where: params,
        data: {
          ...data,

          inverter: data.inverter
            ? {
                connect: data.inverter,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,
          identifier: true,

          inverter: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: StringModel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteStringModel(
    @common.Param() params: StringModelWhereUniqueInput
  ): Promise<StringModel | null> {
    try {
      return await this.service.deleteStringModel({
        where: params,
        select: {
          createdAt: true,
          id: true,
          identifier: true,

          inverter: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/anomalies")
  @ApiNestedQuery(AnomalyFindManyArgs)
  async findAnomalies(
    @common.Req() request: Request,
    @common.Param() params: StringModelWhereUniqueInput
  ): Promise<Anomaly[]> {
    const query = plainToClass(AnomalyFindManyArgs, request.query);
    const results = await this.service.findAnomalies(params.id, {
      ...query,
      select: {
        createdAt: true,
        description: true,
        detectedAt: true,
        id: true,
        severity: true,

        stringField: {
          select: {
            id: true,
          },
        },

        typeField: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/anomalies")
  async connectAnomalies(
    @common.Param() params: StringModelWhereUniqueInput,
    @common.Body() body: AnomalyWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      anomalies: {
        connect: body,
      },
    };
    await this.service.updateStringModel({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/anomalies")
  async updateAnomalies(
    @common.Param() params: StringModelWhereUniqueInput,
    @common.Body() body: AnomalyWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      anomalies: {
        set: body,
      },
    };
    await this.service.updateStringModel({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/anomalies")
  async disconnectAnomalies(
    @common.Param() params: StringModelWhereUniqueInput,
    @common.Body() body: AnomalyWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      anomalies: {
        disconnect: body,
      },
    };
    await this.service.updateStringModel({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/timeSeriesDataItems")
  @ApiNestedQuery(TimeSeriesDataFindManyArgs)
  async findTimeSeriesDataItems(
    @common.Req() request: Request,
    @common.Param() params: StringModelWhereUniqueInput
  ): Promise<TimeSeriesData[]> {
    const query = plainToClass(TimeSeriesDataFindManyArgs, request.query);
    const results = await this.service.findTimeSeriesDataItems(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        metricType: true,

        stringField: {
          select: {
            id: true,
          },
        },

        timestamp: true,
        updatedAt: true,
        value: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/timeSeriesDataItems")
  async connectTimeSeriesDataItems(
    @common.Param() params: StringModelWhereUniqueInput,
    @common.Body() body: TimeSeriesDataWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      timeSeriesDataItems: {
        connect: body,
      },
    };
    await this.service.updateStringModel({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/timeSeriesDataItems")
  async updateTimeSeriesDataItems(
    @common.Param() params: StringModelWhereUniqueInput,
    @common.Body() body: TimeSeriesDataWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      timeSeriesDataItems: {
        set: body,
      },
    };
    await this.service.updateStringModel({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/timeSeriesDataItems")
  async disconnectTimeSeriesDataItems(
    @common.Param() params: StringModelWhereUniqueInput,
    @common.Body() body: TimeSeriesDataWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      timeSeriesDataItems: {
        disconnect: body,
      },
    };
    await this.service.updateStringModel({
      where: params,
      data,
      select: { id: true },
    });
  }
}
