/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  Anomaly as PrismaAnomaly,
  StringModel as PrismaStringModel,
} from "@prisma/client";

export class AnomalyServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.AnomalyCountArgs, "select">): Promise<number> {
    return this.prisma.anomaly.count(args);
  }

  async anomalies(args: Prisma.AnomalyFindManyArgs): Promise<PrismaAnomaly[]> {
    return this.prisma.anomaly.findMany(args);
  }
  async anomaly(
    args: Prisma.AnomalyFindUniqueArgs
  ): Promise<PrismaAnomaly | null> {
    return this.prisma.anomaly.findUnique(args);
  }
  async createAnomaly(args: Prisma.AnomalyCreateArgs): Promise<PrismaAnomaly> {
    return this.prisma.anomaly.create(args);
  }
  async updateAnomaly(args: Prisma.AnomalyUpdateArgs): Promise<PrismaAnomaly> {
    return this.prisma.anomaly.update(args);
  }
  async deleteAnomaly(args: Prisma.AnomalyDeleteArgs): Promise<PrismaAnomaly> {
    return this.prisma.anomaly.delete(args);
  }

  async getStringField(parentId: string): Promise<PrismaStringModel | null> {
    return this.prisma.anomaly
      .findUnique({
        where: { id: parentId },
      })
      .stringField();
  }
}
