/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, IsEnum, ValidateNested } from "class-validator";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { EnumAnomalySeverity } from "./EnumAnomalySeverity";
import { StringModelWhereUniqueInput } from "../../stringModel/base/StringModelWhereUniqueInput";
import { EnumAnomalyTypeField } from "./EnumAnomalyTypeField";

@InputType()
class AnomalyWhereInput {
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  description?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  detectedAt?: DateTimeNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    enum: EnumAnomalySeverity,
  })
  @IsEnum(EnumAnomalySeverity)
  @IsOptional()
  @Field(() => EnumAnomalySeverity, {
    nullable: true,
  })
  severity?: "Option1";

  @ApiProperty({
    required: false,
    type: () => StringModelWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => StringModelWhereUniqueInput)
  @IsOptional()
  @Field(() => StringModelWhereUniqueInput, {
    nullable: true,
  })
  stringField?: StringModelWhereUniqueInput;

  @ApiProperty({
    required: false,
    enum: EnumAnomalyTypeField,
  })
  @IsEnum(EnumAnomalyTypeField)
  @IsOptional()
  @Field(() => EnumAnomalyTypeField, {
    nullable: true,
  })
  typeField?: "Option1";
}

export { AnomalyWhereInput as AnomalyWhereInput };
