/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsDate,
  IsString,
  MaxLength,
  IsOptional,
  IsEnum,
  ValidateNested,
} from "class-validator";
import { Type } from "class-transformer";
import { EnumAnomalySeverity } from "./EnumAnomalySeverity";
import { StringModel } from "../../stringModel/base/StringModel";
import { EnumAnomalyTypeField } from "./EnumAnomalyTypeField";

@ObjectType()
class Anomaly {
  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description!: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  detectedAt!: Date | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    enum: EnumAnomalySeverity,
  })
  @IsEnum(EnumAnomalySeverity)
  @IsOptional()
  @Field(() => EnumAnomalySeverity, {
    nullable: true,
  })
  severity?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: () => StringModel,
  })
  @ValidateNested()
  @Type(() => StringModel)
  @IsOptional()
  stringField?: StringModel | null;

  @ApiProperty({
    required: false,
    enum: EnumAnomalyTypeField,
  })
  @IsEnum(EnumAnomalyTypeField)
  @IsOptional()
  @Field(() => EnumAnomalyTypeField, {
    nullable: true,
  })
  typeField?: "Option1" | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;
}

export { Anomaly as Anomaly };
