/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Anomaly } from "./Anomaly";
import { AnomalyCountArgs } from "./AnomalyCountArgs";
import { AnomalyFindManyArgs } from "./AnomalyFindManyArgs";
import { AnomalyFindUniqueArgs } from "./AnomalyFindUniqueArgs";
import { CreateAnomalyArgs } from "./CreateAnomalyArgs";
import { UpdateAnomalyArgs } from "./UpdateAnomalyArgs";
import { DeleteAnomalyArgs } from "./DeleteAnomalyArgs";
import { StringModel } from "../../stringModel/base/StringModel";
import { AnomalyService } from "../anomaly.service";
@graphql.Resolver(() => Anomaly)
export class AnomalyResolverBase {
  constructor(protected readonly service: AnomalyService) {}

  async _anomaliesMeta(
    @graphql.Args() args: AnomalyCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Anomaly])
  async anomalies(
    @graphql.Args() args: AnomalyFindManyArgs
  ): Promise<Anomaly[]> {
    return this.service.anomalies(args);
  }

  @graphql.Query(() => Anomaly, { nullable: true })
  async anomaly(
    @graphql.Args() args: AnomalyFindUniqueArgs
  ): Promise<Anomaly | null> {
    const result = await this.service.anomaly(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Anomaly)
  async createAnomaly(
    @graphql.Args() args: CreateAnomalyArgs
  ): Promise<Anomaly> {
    return await this.service.createAnomaly({
      ...args,
      data: {
        ...args.data,

        stringField: args.data.stringField
          ? {
              connect: args.data.stringField,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Anomaly)
  async updateAnomaly(
    @graphql.Args() args: UpdateAnomalyArgs
  ): Promise<Anomaly | null> {
    try {
      return await this.service.updateAnomaly({
        ...args,
        data: {
          ...args.data,

          stringField: args.data.stringField
            ? {
                connect: args.data.stringField,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Anomaly)
  async deleteAnomaly(
    @graphql.Args() args: DeleteAnomalyArgs
  ): Promise<Anomaly | null> {
    try {
      return await this.service.deleteAnomaly(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => StringModel, {
    nullable: true,
    name: "stringField",
  })
  async getStringField(
    @graphql.Parent() parent: Anomaly
  ): Promise<StringModel | null> {
    const result = await this.service.getStringField(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
