/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { AnomalyService } from "../anomaly.service";
import { AnomalyCreateInput } from "./AnomalyCreateInput";
import { Anomaly } from "./Anomaly";
import { AnomalyFindManyArgs } from "./AnomalyFindManyArgs";
import { AnomalyWhereUniqueInput } from "./AnomalyWhereUniqueInput";
import { AnomalyUpdateInput } from "./AnomalyUpdateInput";

export class AnomalyControllerBase {
  constructor(protected readonly service: AnomalyService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Anomaly })
  async createAnomaly(
    @common.Body() data: AnomalyCreateInput
  ): Promise<Anomaly> {
    return await this.service.createAnomaly({
      data: {
        ...data,

        stringField: data.stringField
          ? {
              connect: data.stringField,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        description: true,
        detectedAt: true,
        id: true,
        severity: true,

        stringField: {
          select: {
            id: true,
          },
        },

        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Anomaly] })
  @ApiNestedQuery(AnomalyFindManyArgs)
  async anomalies(@common.Req() request: Request): Promise<Anomaly[]> {
    const args = plainToClass(AnomalyFindManyArgs, request.query);
    return this.service.anomalies({
      ...args,
      select: {
        createdAt: true,
        description: true,
        detectedAt: true,
        id: true,
        severity: true,

        stringField: {
          select: {
            id: true,
          },
        },

        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Anomaly })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async anomaly(
    @common.Param() params: AnomalyWhereUniqueInput
  ): Promise<Anomaly | null> {
    const result = await this.service.anomaly({
      where: params,
      select: {
        createdAt: true,
        description: true,
        detectedAt: true,
        id: true,
        severity: true,

        stringField: {
          select: {
            id: true,
          },
        },

        typeField: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Anomaly })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateAnomaly(
    @common.Param() params: AnomalyWhereUniqueInput,
    @common.Body() data: AnomalyUpdateInput
  ): Promise<Anomaly | null> {
    try {
      return await this.service.updateAnomaly({
        where: params,
        data: {
          ...data,

          stringField: data.stringField
            ? {
                connect: data.stringField,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          description: true,
          detectedAt: true,
          id: true,
          severity: true,

          stringField: {
            select: {
              id: true,
            },
          },

          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Anomaly })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteAnomaly(
    @common.Param() params: AnomalyWhereUniqueInput
  ): Promise<Anomaly | null> {
    try {
      return await this.service.deleteAnomaly({
        where: params,
        select: {
          createdAt: true,
          description: true,
          detectedAt: true,
          id: true,
          severity: true,

          stringField: {
            select: {
              id: true,
            },
          },

          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
