/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, McpContext as PrismaMcpContext } from "@prisma/client";

export class McpContextServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.McpContextCountArgs, "select">
  ): Promise<number> {
    return this.prisma.mcpContext.count(args);
  }

  async mcpContexts(
    args: Prisma.McpContextFindManyArgs
  ): Promise<PrismaMcpContext[]> {
    return this.prisma.mcpContext.findMany(args);
  }
  async mcpContext(
    args: Prisma.McpContextFindUniqueArgs
  ): Promise<PrismaMcpContext | null> {
    return this.prisma.mcpContext.findUnique(args);
  }
  async createMcpContext(
    args: Prisma.McpContextCreateArgs
  ): Promise<PrismaMcpContext> {
    return this.prisma.mcpContext.create(args);
  }
  async updateMcpContext(
    args: Prisma.McpContextUpdateArgs
  ): Promise<PrismaMcpContext> {
    return this.prisma.mcpContext.update(args);
  }
  async deleteMcpContext(
    args: Prisma.McpContextDeleteArgs
  ): Promise<PrismaMcpContext> {
    return this.prisma.mcpContext.delete(args);
  }
}
