/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { McpContext } from "./McpContext";
import { McpContextCountArgs } from "./McpContextCountArgs";
import { McpContextFindManyArgs } from "./McpContextFindManyArgs";
import { McpContextFindUniqueArgs } from "./McpContextFindUniqueArgs";
import { CreateMcpContextArgs } from "./CreateMcpContextArgs";
import { UpdateMcpContextArgs } from "./UpdateMcpContextArgs";
import { DeleteMcpContextArgs } from "./DeleteMcpContextArgs";
import { McpContextService } from "../mcpContext.service";
@graphql.Resolver(() => McpContext)
export class McpContextResolverBase {
  constructor(protected readonly service: McpContextService) {}

  async _mcpContextsMeta(
    @graphql.Args() args: McpContextCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [McpContext])
  async mcpContexts(
    @graphql.Args() args: McpContextFindManyArgs
  ): Promise<McpContext[]> {
    return this.service.mcpContexts(args);
  }

  @graphql.Query(() => McpContext, { nullable: true })
  async mcpContext(
    @graphql.Args() args: McpContextFindUniqueArgs
  ): Promise<McpContext | null> {
    const result = await this.service.mcpContext(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => McpContext)
  async createMcpContext(
    @graphql.Args() args: CreateMcpContextArgs
  ): Promise<McpContext> {
    return await this.service.createMcpContext({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => McpContext)
  async updateMcpContext(
    @graphql.Args() args: UpdateMcpContextArgs
  ): Promise<McpContext | null> {
    try {
      return await this.service.updateMcpContext({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => McpContext)
  async deleteMcpContext(
    @graphql.Args() args: DeleteMcpContextArgs
  ): Promise<McpContext | null> {
    try {
      return await this.service.deleteMcpContext(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
