/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { McpContextService } from "../mcpContext.service";
import { McpContextCreateInput } from "./McpContextCreateInput";
import { McpContext } from "./McpContext";
import { McpContextFindManyArgs } from "./McpContextFindManyArgs";
import { McpContextWhereUniqueInput } from "./McpContextWhereUniqueInput";
import { McpContextUpdateInput } from "./McpContextUpdateInput";

export class McpContextControllerBase {
  constructor(protected readonly service: McpContextService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: McpContext })
  async createMcpContext(
    @common.Body() data: McpContextCreateInput
  ): Promise<McpContext> {
    return await this.service.createMcpContext({
      data: data,
      select: {
        contextName: true,
        createdAt: true,
        id: true,
        lastRunAt: true,
        modelType: true,
        parameters: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [McpContext] })
  @ApiNestedQuery(McpContextFindManyArgs)
  async mcpContexts(@common.Req() request: Request): Promise<McpContext[]> {
    const args = plainToClass(McpContextFindManyArgs, request.query);
    return this.service.mcpContexts({
      ...args,
      select: {
        contextName: true,
        createdAt: true,
        id: true,
        lastRunAt: true,
        modelType: true,
        parameters: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: McpContext })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async mcpContext(
    @common.Param() params: McpContextWhereUniqueInput
  ): Promise<McpContext | null> {
    const result = await this.service.mcpContext({
      where: params,
      select: {
        contextName: true,
        createdAt: true,
        id: true,
        lastRunAt: true,
        modelType: true,
        parameters: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: McpContext })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateMcpContext(
    @common.Param() params: McpContextWhereUniqueInput,
    @common.Body() data: McpContextUpdateInput
  ): Promise<McpContext | null> {
    try {
      return await this.service.updateMcpContext({
        where: params,
        data: data,
        select: {
          contextName: true,
          createdAt: true,
          id: true,
          lastRunAt: true,
          modelType: true,
          parameters: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: McpContext })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteMcpContext(
    @common.Param() params: McpContextWhereUniqueInput
  ): Promise<McpContext | null> {
    try {
      return await this.service.deleteMcpContext({
        where: params,
        select: {
          contextName: true,
          createdAt: true,
          id: true,
          lastRunAt: true,
          modelType: true,
          parameters: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
